#!/bin/bash

execdir=$(dirname $(readlink -f $0))

nopdf=$(echo "$@" | grep -F "nopdf")
nohtml=$(echo "$@" | grep -F "nohtm")
nosrc=$(echo "$@" | grep -F "nosrc")
embedfonts=$(echo "$@" | grep -F "embedfonts")
usesvg=$(echo "$@" | grep -F "usesvg")
numbers=$(echo "$@" | grep -F "linenum")

name=${1%.*}

tempname=$(mktemp -u)
tempps=${tempname}.ps
tempmd=${tempname}.md
temppdf=${tempname}.pdf
theme=${execdir}/styles/light.theme
htmlstyle=${execdir}/styles/default.css
texstyle=${execdir}/styles/default.sty
plugin=${execdir}/plugin/plugin.lua
namepdf=${name}.pdf
namehtml=${name}.html

mainfont="Source Sans Pro"

export CODE_FONT="DejaVu Sans Mono"
export TEXT_FONT="Source Sans Pro"

export CLASSPATH=$(dirname $(find /usr/share/java/tla-toolbox/ -type d -name tla2tex))
export ALLOY_CSS=${execdir}/styles/alloy.css
LINE_NUMBERS="0"

if [ -n "$numbers" ]; then
  LINE_NUMBERS="1"
fi

export LINE_NUMBERS

echo Processing:
echo "1. Generating docs:" 

if [ -z "$nopdf" ]; then
  echo '                   ' $1 '->' ${namepdf}
  FORMAT=pdf pp < $1 > ${tempmd}
  pandoc -t latex -M mainfont="${mainfont}" --highlight-style=${theme} --pdf-engine=xelatex --lua-filter=${plugin} --standalone --self-contained --include-in-header ${texstyle} -o ${temppdf} ${tempmd} #> /dev/null 2>&1
  if [ -n "$embedfonts" ]; then
    pdf2ps ${temppdf} ${tempps}
    ps2pdf14 -dPDFSETTINGS=/default -dConvertImagesToIndexed=true -dLZWEncodePages=true ${tempps} ${temppdf}
    rm ${tempps}
  fi
  mv ${temppdf} ${namepdf}
  rm ${tempmd}
fi

if [ -z "$nohtml" ]; then
  echo '                   ' $1 '->' ${namehtml}
  FORMAT=html pp < $1 > ${tempmd}
  pandoc -c ${htmlstyle} -t html --highlight-style=${theme} --self-contained  --lua-filter=${plugin} -o ${namehtml} ${tempmd} #> /dev/null 2>&1
  rm ${tempps} ${temptheme} >/dev/null 2>&1
  rm ${tempmd}
fi
