#!/bin/bash

exec_dir=$(dirname $(readlink -f $0))

extensions="
ocaml:ml
alloy:als
c:c
"

intf_extensions="
ocaml:mli
"

get_extension()
{
  echo "$extensions" | grep "^$1:.*" | sed 's/.*:\(.*\)/\1/'
}

get_intf_extension()
{
  echo "$intf_extensions" | grep "^$1:.*" | sed 's/.*:\(.*\)/\1/'
}

get_langs_in_file()
{
  cat $1 | grep '^```[ ]*[a-zA-Z]\+[ ]*$' | sed 's/```//' | sort | uniq
}

fname=${1%%.${1##*.}}

i=${fname##*.}

if [ x$i = "xi" ] ; then
  fname=${fname%%.i}
fi

outname=$fname

if [ -n "$2" ]; then
  outname=$2/$(basename $fname)
fi

for lang in $(get_langs_in_file $1); do
  if [ x$i = "xi" ] ; then
    ext=$(get_intf_extension $lang)
  else
    ext=$(get_extension $lang)
  fi
  if [ -n "$ext" ] ; then
    echo '    ' ${lang} '->' ${outname}.${ext}
    $exec_dir/md2src -v lang=$lang < $1 > $outname.${ext}
  fi
done
