#!/bin/awk -f

BEGIN {
  in_source_code = 0
  start_src="^```[ ]*"lang"[ ]*$"
  end_src="^```$"
}

{
  if ($0 ~ start_src) { in_source_code = 1; next }
  if (in_source_code && $0 ~ end_src) { in_source_code = 0; printf "\n"; next}
}

in_source_code { print }
